### ISSUE TITLE
AttributeError on `document.findall`

### ISSUE THREAD

**Issue by fmigneault** [PyCQA/doc8#108]
Recent change in version 1.0.0 produces the following error:
https://github.com/PyCQA/doc8/blob/99dca1ddf0d55790b43e42c7246687ba371fa258/src/doc8/utils.py#L60

```python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/bin/doc8", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/doc8/main.py", line 528, in main
    result = doc8(args)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/doc8/main.py", line 403, in doc8
    error_counts = validate(args, files, result=result)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/doc8/main.py", line 271, in validate
    for line_num, code, message in c.report_iter(f):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/doc8/checks.py", line 313, in report_iter
    for issue in checker_func(parsed_file):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/doc8/checks.py", line 252, in _rst_checker
    nodes_lines, first_line = self._extract_node_lines(doc)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/doc8/checks.py", line 182, in _extract_node_lines
    for n in utils.filtered_traverse(doc, filter_systems):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/doc8/utils.py", line 60, in filtered_traverse
    for n in document.findall(include_self=True):
AttributeError: 'document' object has no attribute 'findall'
```

**Comment by ssbarnea** [comment]
Python 3.7 is no longer supported.
