### ISSUE TITLE
AttributeError: 'EntryPoints' object has no attribute 'items'

### ISSUE THREAD

**Issue by pbelskiy** [PyCQA/doc8#112]
Hello!

I have pinned `doc8==1.0.0` but yesterday I got error on Python 3.7 on GitHub actions which is in subject, probably it's because your dependency on [importlib_metadata](https://github.com/python/importlib_metadata) was updated to 5.0.0 yesterday, I think it's good idea to pin major versions in your dependencies? 

https://github.com/pbelskiy/helix-swarm/actions/runs/3173891210/jobs/5170017639

```
2022-10-03T11:48:49.7456304Z doc8 run-test: commands[0] | doc8
2022-10-03T11:48:49.8347316Z Scanning...
2022-10-03T11:48:49.8347798Z Validating...
2022-10-03T11:48:49.8357436Z Traceback (most recent call last):
2022-10-03T11:48:49.8368888Z   File "/home/runner/work/helix-swarm/helix-swarm/.tox/doc8/lib/python3.7/site-packages/stevedore/_cache.py", line 159, in _get_data_for_path
2022-10-03T11:48:49.8461298Z     with open(filename, 'r') as f:
2022-10-03T11:48:49.8466244Z FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.cache/python-entrypoints/18699aac328cd8d1175a899bc48086260e6edf78e85c27c811b2b7ab7e327a5f'
2022-10-03T11:48:49.8466578Z 
2022-10-03T11:48:49.8466750Z During handling of the above exception, another exception occurred:
2022-10-03T11:48:49.8466950Z 
2022-10-03T11:48:49.8467062Z Traceback (most recent call last):
2022-10-03T11:48:49.8467573Z   File "/home/runner/work/helix-swarm/helix-swarm/.tox/doc8/bin/doc8", line 8, in <module>
2022-10-03T11:48:49.8467879Z     sys.exit(main())
2022-10-03T11:48:49.8468375Z   File "/home/runner/work/helix-swarm/helix-swarm/.tox/doc8/lib/python3.7/site-packages/doc8/main.py", line 528, in main
2022-10-03T11:48:49.8468714Z     result = doc8(args)
2022-10-03T11:48:49.8469186Z   File "/home/runner/work/helix-swarm/helix-swarm/.tox/doc8/lib/python3.7/site-packages/doc8/main.py", line 403, in doc8
2022-10-03T11:48:49.8469561Z     error_counts = validate(args, files, result=result)
2022-10-03T11:48:49.8470080Z   File "/home/runner/work/helix-swarm/helix-swarm/.tox/doc8/lib/python3.7/site-packages/doc8/main.py", line 239, in validate
2022-10-03T11:48:49.8470425Z     for c in fetch_checks(cfg):
2022-10-03T11:48:49.8470927Z   File "/home/runner/work/helix-swarm/helix-swarm/.tox/doc8/lib/python3.7/site-packages/doc8/main.py", line 183, in fetch_checks
2022-10-03T11:48:49.8471530Z     namespace="doc8.extension.check", invoke_on_load=True, invoke_args=(cfg.copy(),)
2022-10-03T11:48:49.8472117Z   File "/home/runner/work/helix-swarm/helix-swarm/.tox/doc8/lib/python3.7/site-packages/stevedore/extension.py", line 136, in __init__
2022-10-03T11:48:49.8472459Z     verify_requirements)
2022-10-03T11:48:49.8472975Z   File "/home/runner/work/helix-swarm/helix-swarm/.tox/doc8/lib/python3.7/site-packages/stevedore/extension.py", line 218, in _load_plugins
2022-10-03T11:48:49.8473377Z     for ep in self.list_entry_points():
2022-10-03T11:48:49.8473953Z   File "/home/runner/work/helix-swarm/helix-swarm/.tox/doc8/lib/python3.7/site-packages/stevedore/extension.py", line 207, in list_entry_points
2022-10-03T11:48:49.8474362Z     eps = list(_cache.get_group_all(self.namespace))
2022-10-03T11:48:49.8474907Z   File "/home/runner/work/helix-swarm/helix-swarm/.tox/doc8/lib/python3.7/site-packages/stevedore/_cache.py", line 179, in get_group_all
2022-10-03T11:48:49.8475272Z     data = self._get_data_for_path(path)
2022-10-03T11:48:49.8475896Z   File "/home/runner/work/helix-swarm/helix-swarm/.tox/doc8/lib/python3.7/site-packages/stevedore/_cache.py", line 162, in _get_data_for_path
2022-10-03T11:48:49.8476270Z     data = _build_cacheable_data(path)
2022-10-03T11:48:49.8476816Z   File "/home/runner/work/helix-swarm/helix-swarm/.tox/doc8/lib/python3.7/site-packages/stevedore/_cache.py", line 110, in _build_cacheable_data
2022-10-03T11:48:49.8477207Z     for name, group_data in real_groups.items():
2022-10-03T11:48:49.8477592Z AttributeError: 'EntryPoints' object has no attribute 'items'
2022-10-03T11:48:49.8478094Z ERROR: InvocationError for command /home/runner/work/helix-swarm/helix-swarm/.tox/doc8/bin/doc8 (exited with code 1)
```

**Comment by gonchik** [comment]
Any plans to wrap up ? :)

**Comment by ssbarnea** [comment]
py37 is no longer supported.
