### ISSUE TITLE
how to set `ignore-path-errors`in a pyproject.toml

### ISSUE THREAD

**Issue by 12rambau** [PyCQA/doc8#133]
I'm using a pyproject.toml file to setup my lib tools and I would like to include doc8. I wrote the following:

```toml
[tool.doc8]
ignore = ["D001"] # we follow a 1 line = 1 paragraph style
ignore-path-errors = "docs/source/index.rst;D000"
```

but when I try to run doc8 I got the following error : 

> Traceback (most recent call last):
  File "/Users/pierrickrambaud/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/pierrickrambaud/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/pierrickrambaud/.cache/pre-commit/repos8mnpfl6/py_env-python3/lib/python3.8/site-packages/doc8/__main__.py", line 20, in <module>
    sys.exit(main.main())
  File "/Users/pierrickrambaud/.cache/pre-commit/repos8mnpfl6/py_env-python3/lib/python3.8/site-packages/doc8/main.py", line 534, in main
    result = doc8(args)
  File "/Users/pierrickrambaud/.cache/pre-commit/repos8mnpfl6/py_env-python3/lib/python3.8/site-packages/doc8/main.py", line 385, in doc8
    cfg = extract_config(args)
  File "/Users/pierrickrambaud/.cache/pre-commit/repos8mnpfl6/py_env-python3/lib/python3.8/site-packages/doc8/main.py", line 167, in extract_config
    cfg = from_toml(cfg_file)
  File "/Users/pierrickrambaud/.cache/pre-commit/repos8mnpfl6/py_env-python3/lib/python3.8/site-packages/doc8/main.py", line 149, in from_toml
    value = parse_ignore_path_errors(value)
  File "/Users/pierrickrambaud/.cache/pre-commit/repos8mnpfl6/py_env-python3/lib/python3.8/site-packages/doc8/main.py", line 79, in parse_ignore_path_errors
    path, ignored_errors = path.split(";", 1)
ValueError: not enough values to unpack (expected 2, got 1)

What I don't understand is that I do use a ";" in my parameter string an I do have 2 values: 
- docs/source/index.rs
- D000

Am I missing something ?

**Comment by 12rambau** [comment]
in a `pyproject.toml`, it expect a list so setting it as: 

```toml
ignore-path-errors = ["docs/source/index.rst;D000"]
```

THere is no specific documentation for `pyproject.toml` (some tuning needs to be made from `setup.cfg` example) so I will close this one here.
